### ISSUE TITLE
6X00 series GPU support (gfx10)

### ISSUE THREAD

**Issue by bennmann** [ROCmSoftwarePlatform/rocWMMA#155]
6X00 series has ray tracing capabilities, are they not supported for rocWMMA at all for some of these gemm functions?

**Comment by cgmillette** [comment]
Hi there, thanks for reaching out! 

The 6X00 (gfx10) series cards are based on the RDNA2 architecture which has special raytracing hardware units which accelerate that type of application. These are pretty specialized for rendering pipelines, and are not currently in the scope of rocWMMA.

The next generation (gfx11) of cards with RDNA3 architecture have different hardware 'AI acceleration' units, which do fall within the scope of rocWMMA. They provide more generalized support for matrix multiplication (data type & layout, block sizes, etc.) that can be leveraged by a wide variety of AI or other HPC applications. rocWMMA's purpose is to facilitate using these hardware units in an approachable fashion with block-wise multiplication. 

See the differences here:
https://www.amd.com/en/technologies/rdna

I hope that helps!

**Comment by bennmann** [comment]
Thank you for your reply and for any additional consideration.

If anyone found a way to use Ray tracing for matrix multiplication it could
be a huge boon for all AMD users, including gfx11 users. It is beyond my
layman skills, just intuition.
