### ISSUE TITLE
Support gfx1030

### ISSUE THREAD

**Issue by Bengt** [ROCmSoftwarePlatform/rocWMMA#31]
Hello,

as recently stated, ROCm supports gfx1030 products officially:

https://github.com/RadeonOpenCompute/ROCm/issues/1714#issuecomment-1128327143

However, this ROCm library does not target the gfx1030 instruction set architecture (ISA):

https://github.com/ROCmSoftwarePlatform/rocWMMA/blob/develop/CMakeLists.txt#L85

So please add support in this library in order to get in line with the official support.

Kind Regards,
Bengt Lüers

**Comment by saadrahim** [comment]
rocWMMA does not support the NAVI GPU architectures. There is no plan to add support for them.

**Comment by Bengt** [comment]
Hi, @saadrahim,

thanks for clarifying. I did not know that this library is intended for CDNA architecture GPUs, only.

Could you please also comment on what this means for the support statement? It seems to me, that full library coverage actually only exists for the enterprise MI100 GPUs implementing the CDNA architecture. In your earlier statement you said that the workstation 6800W and V620 GPU products implementing the RDNA2 GPUs are supported. What do you mean by official support?

Kind Regards,
Bengt Lüers
